server {
    listen 80;
    server_name _;
    root /var/www/html/web;
    index index.php;
    client_max_body_size 12m;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ ^/index\.php(?:$|/) {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass php:9000;
    }

    location ~ \.php$ {
        return 404;
    }
}
